#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2.5
bspc config window_gap           1.5
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# fix java error
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

# wallpaper
feh --bg-fill /home/byt3/Wallpapers/wall.jpg &

# polybar
killall -q polybar
sleep 1
polybar &

